dataset:
  name: iemocap
  dataset_dir: './data/'
  emotion: angry
  classes: 2
  batch_size: 32
  num_workers: 4
  shuffle: True
  seed: 42

criterion:
  name: ce

optimizer:
  name: adamw
  lr: 0.002
  weight_decay: 0.0

scheduler:
  name: cosine
  lr_gamma: 0.99
  lr_min: 0

run:
  experiment: "default"
  n_epochs: 200
  batch_size: 32
  use_cuda: 1
  gpu_id: 0
  deterministic: 1
  log_interval: 200
  train_noise: 0

quantize:
  w_bit: 32
  in_bit: 32
  v_pi: 4.36
  v_max: 10.8

noise:
  phase_noise_std: 0
  gamma_noise_std:
  crosstalk_factor: 0
  random_state: 42

ic: # identity calibration
  alg: zcd # [zgd, ztp, zcd]
  adaptive: 1
  best_record: 1

sparse:
  bp_forward_weight_sparsity: 0
  bp_feedback_weight_sparsity: 0
  bp_feedback_alg: "topk"
  bp_feedback_norm: 0
  bp_input_sparsity: 0
  bp_spatial_sparsity: 0
  bp_column_sparsity: 0
  bp_input_norm: 0
  bp_rank: 8
  bp_rank_alg: "topk"
  bp_rank_sign: 0

regularization:
  lambda_1 : 0
  lambda_2 : 0
  lambda_3 : 0

model:
  name: LMF

  input_dims: [80,36,300,20]
  hidden_dims: [32,32,64]
  sub_out_dims: [31,31,63]
  dropouts: [0.3,0.1,0.15,0.5]
  output_dim: 2
  rank: 8

  TT_ATTN: 0
  n_layers: 2
  n_head: 3
  ATTN_rank: 4
  
  TT_FUSION: 0
  TT_FUSION_rank: 4

  TT_SUBNET: 0
  TT_SUBNET_rank: 4
  tensor_type: 'TTM'

debug:
  verbose: 1

