dataset:
  name: iemocap
  dataset_dir: './data/'
  emotion: angry
  classes: 2
  batch_size: 64
  num_workers: 4
  shuffle: True
  seed: 0

criterion:
  name: ce

optimizer:
  name: adam
  factor_lr: 0.003
  lr: 0.0005
  weight_decay: 0.001

scheduler:
  name: cosine
  lr_gamma: 0.99
  lr_min: 0  

run:
  n_epochs: 100
  model_path_dir: './tt_models/'
  signiture: 'lmf'
  patience: 50

  patience: 10
  factor: 0.1
  log_interval: 10
  save_model: True
  save_interval: 10
  save_best: True
  save_path: 'models/TT'
  resume: False

model:
  name: LMF

  # input_dims: [80,36,300,20]
  input_dims: [74,35,300,20]
  # hidden_dims: [8,4,64]
  # sub_out_dims: [8,4,32]
  hidden_dims: [32,32,64]
  sub_out_dims: [31,31,63]
  dropouts: [0.3,0.1,0.15,0.5]
  output_dim: 2
  rank: 8

  FUSION_TYPE: 'add'
  # FUSION_TYPE: 'replace'

  TT_ATTN: False
  n_layers: 2
  n_head: 3
  ATTN_rank: 4
  
  TT_FUSION: False
  TT_FUSION_rank: 4

  TT_SUBNET: False
  TT_SUBNET_rank: 4
  tensor_type: 'TTM'