dataset:
  name: iemocap
  dataset_dir: './data/'
  emotion: angry
  classes: 2
  batch_size: 64
  num_workers: 4
  shuffle: True
  seed: 42

criterion:
  name: ce

optimizer:
  name: adam
  factor_lr: 0.003
  lr: 0.0005
  weight_decay: 0.001

scheduler:
  name: cosine
  lr_gamma: 0.99
  lr_min: 0  

run:
  n_epochs: 100
  model_path_dir: './tt_models/'
  signiture: 'lmf'
  patience: 50

  patience: 10
  factor: 0.1
  log_interval: 10
  save_model: True
  save_interval: 10
  save_best: True
  save_path: 'models/TT'
  resume: False

model:
  name: TOMFUN
  # mzi_noise: True
  mzi_noise: False

  miniblock: 8
  mode: "weight"
  # mode: "usv"
  # mode: "phase"
  act_thres: 2.0

  # input_dims: [80,36,300,20]
  input_dims: [74,35,300,20]

  hidden_dims: [16,16,64]
  FUSION_TYPE: 'add'
  sub_out_dims: [16,16,32]
  # sub_out_dims: [7,3,63]
  FUSION_TYPE: 'replace'
  sub_out_dims: [16,16,32]

  # TT_ATTN: False
  TT_ATTN: True
  n_layers: 2
  n_head: 3
  ATTN_rank: 4
  
  # TT_FUSION: False
  TT_FUSION: True
  TT_FUSION_rank: 4

  TT_SUBNET: False
  # TT_SUBNET: True
  TT_SUBNET_rank: 4
  tensor_type: 'TTM'

quantize:
  w_bit: 32
  in_bit: 32
  v_pi: 4.36
  v_max: 10.8

noise:
  phase_noise_std: 0
  gamma_noise_std: 0
  phase_bias: 1
  gamma_noise_std: 0.002
  crosstalk_factor: 0.005
  random_state: 42

ic: # identity calibration
  alg: zcd # [zgd, ztp, zcd]
  adaptive: 1
  best_record: 1

sl: # subspace learning
  noisy_identity: 0