dataset:
  name: iemocap
  dataset_dir: './data/'
  emotion: angry
  classes: 2
  batch_size: 64
  num_workers: 4
  shuffle: True
  seed: 42

criterion:
  name: ce

optimizer:
  name: adam
  factor_lr: 0.003
  lr: 0.0005
  weight_decay: 0.001

scheduler:
  name: cosine
  lr_gamma: 0.99
  lr_min: 0  

run:
  n_epochs: 50
  model_path_dir: './tt_models/'
  signiture: 'lmf'
  patience: 20

model:
  name: LMF

  # input_dims: [80,36,300,20]
  input_dims: [74,35,300,20]

  hidden_dims: [8,4,64]
  FUSION_TYPE: 'add'
  sub_out_dims: [8,4,32]
  # sub_out_dims: [7,3,63]
  # FUSION_TYPE: 'replace'
  # sub_out_dims: [8,4,64]

  # hidden_dims: [32,32,64]
  # # FUSION_TYPE: 'add'
  # # sub_out_dims: [32,32,64]
  # # sub_out_dims: [31,31,63]
  # FUSION_TYPE: 'replace'
  # sub_out_dims: [32,32,64]
  
  dropouts: [0.3,0.1,0.15,0.5]
  output_dim: 2
  rank: 8
  
  TT_ATTN: False
  # TT_ATTN: True
  n_layers: 2
  n_head: 3
  ATTN_rank: 4
  
  TT_FUSION: False
  # TT_FUSION: True
  TT_FUSION_rank: 4

  TT_SUBNET: False
  # TT_SUBNET: True
  TT_SUBNET_rank: 4
  # tensor_type: 'TTM'
  tensor_type: 'TensorTrainMatrix'  